#server:
#  applicationConnectors:
#    - type: http
#      port: 8080
#  adminConnectors:
#    - type: http
#      port: 9001
#
#
## MySQL
##database:
##  driverClass: com.mysql.jdbc.Driver
##  user: jana
##  password: jana@123
##  url: jdbc:mysql://localhost:3306/schema2
##  properties:
##    charSet: UTF-8
#
## Database settings.
#database:
#  # the name of your JDBC driver
#  driverClass: org.h2.Driver
#  # the username
#  user: sa
#  # the password
#  password: sa
#  # the JDBC URL
#  url: jdbc:h2:./target/example
#
#
## Logging settings.
#logging:
#  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: DEBUG
#  # Logger-specific levels.
#  loggers:
#    # Sets the level for 'com.example.app' to DEBUG.
#    org.jana.dropwizard: DEBUG
#    # Redirects SQL logs to a separate file
#    org.hibernate.SQL:
#      level: DEBUG